apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: mgmt
      port: 8080
      targetPort: mgmt
{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
    - name: smtps
      port: {{ .Values.service.ports.smtps }}
      targetPort: smtps
    - name: submission
      port: {{ .Values.service.ports.submission }}
      targetPort: submission
    - name: imap
      port: {{ .Values.service.ports.imap }}
      targetPort: imap
    - name: imaps
      port: {{ .Values.service.ports.imaps }}
      targetPort: imaps
    - name: pop3
      port: {{ .Values.service.ports.pop3 }}
      targetPort: pop3
    - name: pop3s
      port: {{ .Values.service.ports.pop3s }}
      targetPort: pop3s
    - name: sieve
      port: {{ .Values.service.ports.sieve }}
      targetPort: sieve
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
    - name: mgmt
      port: {{ .Values.service.ports.mgmt }}
      targetPort: mgmt
{{- end }}
{{- if .Values.serviceExpose.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-expose
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  {{- if .Values.serviceExpose.annotations }}
  annotations: {{- toYaml .Values.serviceExpose.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceExpose.type }}
  {{- if .Values.serviceExpose.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceExpose.loadBalancerIP | quote }}
  {{- end }}
  {{- if .Values.serviceExpose.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.serviceExpose.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.serviceExpose.ports.smtp }}
    - name: smtp
      port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
    {{- end }}
    {{- if .Values.serviceExpose.ports.smtps }}
    - name: smtps
      port: {{ .Values.service.ports.smtps }}
      targetPort: smtps
    {{- end }}
    {{- if .Values.serviceExpose.ports.submission }}
    - name: submission
      port: {{ .Values.service.ports.submission }}
      targetPort: submission
    {{- end }}
    {{- if .Values.serviceExpose.ports.imap }}
    - name: imap
      port: {{ .Values.service.ports.imap }}
      targetPort: imap
    {{- end }}
    {{- if .Values.serviceExpose.ports.imaps }}
    - name: imaps
      port: {{ .Values.service.ports.imaps }}
      targetPort: imaps
    {{- end }}
    {{- if .Values.serviceExpose.ports.pop3 }}
    - name: pop3
      port: {{ .Values.service.ports.pop3 }}
      targetPort: pop3
    {{- end }}
    {{- if .Values.serviceExpose.ports.pop3s }}
    - name: pop3s
      port: {{ .Values.service.ports.pop3s }}
      targetPort: pop3s
    {{- end }}
    {{- if .Values.serviceExpose.ports.sieve }}
    - name: sieve
      port: {{ .Values.service.ports.sieve }}
      targetPort: sieve
    {{- end }}
    {{- if .Values.serviceExpose.ports.http }}
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
    {{- end }}
    {{- if .Values.serviceExpose.ports.https }}
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
    {{- end }}
    {{- if .Values.serviceExpose.ports.mgmt }}
    - name: mgmt
      port: {{ .Values.service.ports.mgmt }}
      targetPort: mgmt
    {{- end }}
{{- end }}