---
# Default values for stalwart with RocksDB.
# This is a YAML-formatted file.

## Enable recoveryAdmin on first time startup
# recoveryAdmin:
#   enabled: false
#   username: admin
#   password: change-me

## Configure storage backend for RocksDB
config:
  "@type": RocksDb
  path: /var/lib/stalwart

## RocksDB uses local storage, therefore persistence must be enabled
persistence:
  enabled: true
  storageClass: change-me

## Optional: Enable Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: mail.example.com
      paths:
        - path: /
          pathType: Prefix
          portName: https
  tls:
    - secretName: mail-example-com-tls
      hosts:
        - mail.example.com

## Optional: Mount TLS Certificate into container
certificate:
  enabled: true
  secretName: mail-example-com-tls
